//! Combat tick, plus the named walks that lead up to one. `tick_combat` is
//! the per-tick top-of-loop call from `llm_driver` (chase, face, attack).
//! The walking itself belongs to `walk`, whose one loop serves all of these
//! — what differs between a chase, an approach and a pickup is a row in its
//! target table, not a loop of its own.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use onlinerpg_shared::ability::{AbilityId, GUARDIAN_WARD_DURATION_MS, GUARDIAN_WARD_MANA_COST};
use onlinerpg_shared::{CharacterClass, ClientMessage, PlayerId};
use tokio::sync::Mutex;
use tracing::{error, info, warn};

use crate::state::{SharedState, DEFAULT_ATTACK_COOLDOWN};

/// Path to animation durations JSON (generated by tools/extract-animation-durations.mjs).
/// Relative to agent-client working directory.
const ANIMATION_DURATIONS_PATH: &str = "data/animation_durations.json";

use super::walk::{walk, LostReason, WalkTo, Walked};

/// The server's gate for opening a chest or a prop (`CHEST_INTERACT_RANGE`,
/// `PROP_INTERACT_RANGE`), which it measures from the chest — not from where
/// we walked to.
pub(super) const CHEST_INTERACT_RANGE: f32 = 2.5;
/// Slack left under that gate for overshoot and for the lag between our
/// position and the server's.
const CHEST_ARRIVE_MARGIN: f32 = 0.5;

/// How close to stop to the walk target, given how far that target sits from
/// the thing being opened. A clutter prop is a collision pillar, so we walk to
/// the cell beside it instead — and that metre comes out of our margin.
pub(super) fn chest_arrive_range(gap: f32) -> f32 {
    (CHEST_INTERACT_RANGE - gap - CHEST_ARRIVE_MARGIN).max(0.5)
}

/// Load the attack (slash1) animation duration from the shared JSON file.
/// Returns the duration as milliseconds, or the default if loading fails.
pub(super) fn load_attack_cooldown() -> Duration {
    let Ok(text) = std::fs::read_to_string(ANIMATION_DURATIONS_PATH) else {
        warn!("Could not read {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return DEFAULT_ATTACK_COOLDOWN;
    };

    // Structure: { "combat_melee": { "slash1": 1.533, ... }, ... }
    let Ok(data) = serde_json::from_str::<HashMap<String, HashMap<String, f64>>>(&text) else {
        warn!("Could not parse {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return DEFAULT_ATTACK_COOLDOWN;
    };

    if let Some(duration_secs) = data.get("combat_melee").and_then(|m| m.get("slash1")) {
        let ms = (*duration_secs * 1000.0) as u64;
        info!("Loaded attack cooldown from animation data: {ms}ms");
        Duration::from_millis(ms)
    } else {
        warn!("slash1 animation not found in {ANIMATION_DURATIONS_PATH}, using default");
        DEFAULT_ATTACK_COOLDOWN
    }
}

/// Execute one combat tick: check if target is alive and in range, chase or attack.
/// Returns whether to keep targeting; false means combat ended.
pub(super) async fn tick_combat(
    state: &Arc<Mutex<SharedState>>,
    monster_id: &str,
    sprint: Option<bool>,
) -> bool {
    // Chase until in range (handles monster movement during chase)
    match chase_monster(state, monster_id, sprint).await {
        ChaseResult::InRange => {}
        ChaseResult::Lost(reason) => {
            info!("Combat ended: monster {monster_id} lost during chase ({reason:?})");
            let mut s = state.lock().await;
            let note = match reason {
                // Gone from the world state right after we were trading
                // blows — usually our kill, but it may also have simply
                // walked out of sight, so don't assert a corpse.
                LostReason::TargetGone => format!(
                    "[CombatEnded] {monster_id} is no longer there — you may have killed it, \
                     or it left your sight. Check the ground for loot, then decide your \
                     next move."
                ),
                other => format!(
                    "[CombatEnded] You broke off from {monster_id} — {}.",
                    other.clause()
                ),
            };
            s.push_agent_event(note);
            return false;
        }
        ChaseResult::Error => {
            info!("Combat ended: error during chase of {monster_id}");
            let mut s = state.lock().await;
            s.push_agent_event(format!(
                "[CombatEnded] You lost {monster_id} — something went wrong on the way. \
                 Decide your next move."
            ));
            return false;
        }
    }

    // Face the monster before attacking (matches web client behavior)
    {
        let mut s = state.lock().await;
        if let Some(face_cmd) = s.face_monster_command(monster_id) {
            if let Err(e) = s.send_command(face_cmd).await {
                error!("Failed to send face-monster move: {e}");
                return false;
            }
        }
    }

    // Send attack
    {
        let mut s = state.lock().await;
        if ward_due(&s, Instant::now()) {
            s.ward_ready_at =
                Some(Instant::now() + Duration::from_millis(GUARDIAN_WARD_DURATION_MS));
            let cmd = ClientMessage::UseAbility {
                ability: AbilityId::GuardianWard,
                monster_id: None,
                target_player_id: None,
            };
            if let Err(e) = s.send_command(cmd).await {
                error!("Failed to send Guardian Ward: {e}");
            }
        }
        let cmd = ClientMessage::PlayerAttack {
            monster_id: monster_id.to_string(),
        };
        if let Err(e) = s.send_command(cmd).await {
            error!("Failed to send attack: {e}");
            return false;
        }
    }

    true
}

/// A knight opens every fight under Guardian Ward and renews it as it lapses.
fn ward_due(s: &SharedState, now: Instant) -> bool {
    s.self_player
        .as_ref()
        .is_some_and(|p| p.class == CharacterClass::Knight)
        && s.self_mana
            .is_some_and(|(mana, _)| mana >= GUARDIAN_WARD_MANA_COST)
        && s.ward_ready_at.is_none_or(|at| now >= at)
}

pub(super) enum ChaseResult {
    InRange,
    Lost(LostReason),
    Error,
}

impl From<Walked> for ChaseResult {
    fn from(w: Walked) -> Self {
        match w {
            Walked::Arrived => Self::InRange,
            Walked::Lost(reason) => Self::Lost(reason),
            Walked::Error => Self::Error,
        }
    }
}

/// Chase the monster until we're in attack range.
pub(super) async fn chase_monster(
    state: &Arc<Mutex<SharedState>>,
    monster_id: &str,
    sprint: Option<bool>,
) -> ChaseResult {
    walk(state, &WalkTo::Monster(monster_id), false, sprint)
        .await
        .into()
}

/// Walk up to another character and stop a polite metre short, following
/// them if they move.
pub(super) async fn approach_player(
    state: &Arc<Mutex<SharedState>>,
    player_id: &PlayerId,
    sprint: Option<bool>,
) -> ChaseResult {
    walk(state, &WalkTo::Character(player_id), false, sprint)
        .await
        .into()
}

/// The follow task's approach: the same walk, but its steps are background —
/// the task outlives the turn, and steps landing mid-settle must not pass for
/// the running action's result. Unset sprint walks: the target sets the pace,
/// so sprinting the catch-ups buys no ground for the food.
pub(super) async fn follow_player(
    state: &Arc<Mutex<SharedState>>,
    player_id: &PlayerId,
    sprint: Option<bool>,
) -> ChaseResult {
    walk(
        state,
        &WalkTo::Character(player_id),
        true,
        sprint.or(Some(false)),
    )
    .await
    .into()
}

/// Walk to a ground item and stop inside pickup range. The item vanishing
/// (picked up or despawned) ends it as `Lost`.
pub(super) async fn walk_to_ground_item(
    state: &Arc<Mutex<SharedState>>,
    instance_id: u64,
    sprint: Option<bool>,
) -> ChaseResult {
    walk(state, &WalkTo::GroundItem(instance_id), false, sprint)
        .await
        .into()
}

/// Walk to a fixed position on a floor, stopping within `arrive_range` of it.
pub(super) async fn walk_to_point(
    state: &Arc<Mutex<SharedState>>,
    pos: onlinerpg_shared::Position,
    floor_level: i8,
    arrive_range: f32,
    sprint: Option<bool>,
) -> ChaseResult {
    walk(
        state,
        &WalkTo::Point {
            pos,
            floor_level,
            arrive_range,
        },
        false,
        sprint,
    )
    .await
    .into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_knight_with_mana_wards_once_per_duration() {
        let (mut s, _rx) = crate::state::tests::test_state();
        let mut me = crate::state::tests::test_player(0.0, 0.0);
        me.class = CharacterClass::Knight;
        s.self_player = Some(me);
        let now = Instant::now();
        s.self_mana = Some((GUARDIAN_WARD_MANA_COST - 1, 10));
        assert!(!ward_due(&s, now));
        s.self_mana = Some((GUARDIAN_WARD_MANA_COST, 10));
        assert!(ward_due(&s, now));
        s.ward_ready_at = Some(now + Duration::from_millis(GUARDIAN_WARD_DURATION_MS));
        assert!(!ward_due(&s, now));
        s.self_player.as_mut().unwrap().class = CharacterClass::Barbarian;
        s.ward_ready_at = None;
        assert!(!ward_due(&s, now));
    }

    /// Wherever we stop, the server has to agree we are in range — it measures
    /// from the chest, we walk to a cell that can be a metre off it.
    #[test]
    fn a_chest_walk_ends_inside_the_server_range() {
        // 0.0: the treasure chest, walked onto directly. 1.0: the cell beside
        // a clutter prop, the only case `beside_prop` can produce.
        for gap in [0.0, 1.0] {
            let stop = gap + chest_arrive_range(gap);
            assert!(
                stop < CHEST_INTERACT_RANGE,
                "stopping {stop}m from a chest {gap}m off the walk target is outside the gate"
            );
        }
    }
}
