//! Combat tick + chase loop. Combat lives in two layers: `tick_combat`
//! is the per-tick top-of-loop call from `llm_driver` (chase, face,
//! attack); `chase_target` is the pathfinding-driven approach loop that
//! polls the target position and re-routes when it moves. The same loop
//! also powers `approach_player`, the non-combat "walk up to a character
//! and stop a polite metre short" move. Constants at the top tune both
//! the chase cadence and the attack-cooldown derived from animation data.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use onlinerpg_shared::{ClientMessage, PlayerId};
use tokio::sync::Mutex;
use tracing::{error, info, warn};

use crate::geom::PlanarDelta;
use crate::state::SharedState;

/// Minimum distance to a monster before attacking (matches client-side threshold).
const ATTACK_RANGE: f32 = 2.0;
/// Fallback attack cooldown if animation data is unavailable.
const DEFAULT_ATTACK_COOLDOWN_MS: u64 = 1500;
/// Path to animation durations JSON (generated by tools/extract-animation-durations.mjs).
/// Relative to agent-client working directory.
const ANIMATION_DURATIONS_PATH: &str = "data/animation_durations.json";

use super::movement::{open_blocking_door, travel_ms, MAX_STEP_DIST};

/// How often to poll when waiting (no active step to send), in ms.
const CHASE_IDLE_TICK_MS: u64 = 200;
/// Maximum chase duration before giving up (seconds).
const MAX_CHASE_SECS: f32 = 15.0;
/// Give up chasing monsters farther than this from the agent. Prevents NPC
/// guards from running far off their patrol to engage distant threats.
const MAX_CHASE_DISTANCE: f32 = 20.0;
/// How far the monster must move from our last target before we re-route.
const REROUTE_THRESHOLD: f32 = 1.5;

/// How many shut doors one chase may open on its way to the target.
const MAX_CHASE_DOORS: usize = 2;
/// Polite stop distance when walking up to another character (player or
/// NPC): close enough to talk, far enough that the models don't overlap.
const APPROACH_RANGE: f32 = 1.0;
/// Maximum approach duration before giving up (seconds). Longer than the
/// combat chase: an approach target can be anywhere inside the sight radius.
const MAX_APPROACH_SECS: f32 = 30.0;
/// Stop distance for ground items, inside the server's 2.5 m pickup gate
/// (`MAX_PICKUP_DISTANCE`) so overshoot and float error can't push the
/// PickupItem send back out of range.
const PICKUP_ARRIVE_RANGE: f32 = 2.0;
/// Maximum walk-to-item duration before giving up (seconds). Shorter than
/// an approach: the target never moves away.
const MAX_PICKUP_WALK_SECS: f32 = 12.0;
/// The server's gate for opening a chest or a prop (`CHEST_INTERACT_RANGE`,
/// `PROP_INTERACT_RANGE`), which it measures from the chest — not from where
/// we walked to.
pub(super) const CHEST_INTERACT_RANGE: f32 = 2.5;
/// Slack left under that gate for overshoot and for the lag between our
/// position and the server's.
const CHEST_ARRIVE_MARGIN: f32 = 0.5;
/// Maximum walk-to-point duration before giving up (seconds). A point is only
/// ever walked to from inside its own room, so this is a stuck-detector, not
/// a travel budget.
const MAX_POINT_WALK_SECS: f32 = 15.0;

/// How close to stop to the walk target, given how far that target sits from
/// the thing being opened. A clutter prop is a collision pillar, so we walk to
/// the cell beside it instead — and that metre comes out of our margin.
pub(super) fn chest_arrive_range(gap: f32) -> f32 {
    (CHEST_INTERACT_RANGE - gap - CHEST_ARRIVE_MARGIN).max(0.5)
}

/// Load the attack (slash1) animation duration from the shared JSON file.
/// Returns the duration as milliseconds, or the default if loading fails.
pub(super) fn load_attack_cooldown() -> Duration {
    let Ok(text) = std::fs::read_to_string(ANIMATION_DURATIONS_PATH) else {
        warn!("Could not read {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS);
    };

    // Structure: { "combat_melee": { "slash1": 1.533, ... }, ... }
    let Ok(data) = serde_json::from_str::<HashMap<String, HashMap<String, f64>>>(&text) else {
        warn!("Could not parse {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS);
    };

    if let Some(duration_secs) = data.get("combat_melee").and_then(|m| m.get("slash1")) {
        let ms = (*duration_secs * 1000.0) as u64;
        info!("Loaded attack cooldown from animation data: {ms}ms");
        Duration::from_millis(ms)
    } else {
        warn!("slash1 animation not found in {ANIMATION_DURATIONS_PATH}, using default");
        Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS)
    }
}

/// Execute one combat tick: check if target is alive and in range, chase or attack.
/// Returns Some(monster_id) to keep targeting, or None if combat ended.
pub(super) async fn tick_combat(
    state: &Arc<Mutex<SharedState>>,
    monster_id: String,
) -> Option<String> {
    // Chase until in range (handles monster movement during chase)
    match chase_monster(state, &monster_id, None).await {
        ChaseResult::InRange => {}
        ChaseResult::Lost(reason) => {
            info!("Combat ended: monster {monster_id} lost during chase ({reason:?})");
            let mut s = state.lock().await;
            let note = match reason {
                // Gone from the world state right after we were trading
                // blows — usually our kill, but it may also have simply
                // walked out of sight, so don't assert a corpse.
                LostReason::TargetGone => format!(
                    "[CombatEnded] {monster_id} is no longer there — you may have killed it, \
                     or it left your sight. Check the ground for loot, then decide your \
                     next move."
                ),
                other => format!(
                    "[CombatEnded] You broke off from {monster_id} — {}.",
                    other.clause()
                ),
            };
            s.push_agent_event(note);
            return None;
        }
        ChaseResult::Error => {
            info!("Combat ended: error during chase of {monster_id}");
            let mut s = state.lock().await;
            s.push_agent_event(format!(
                "[CombatEnded] You lost {monster_id} — something went wrong on the way. \
                 Decide your next move."
            ));
            return None;
        }
    }

    // Face the monster before attacking (matches web client behavior)
    {
        let mut s = state.lock().await;
        if let Some(face_cmd) = s.face_monster_command(&monster_id) {
            if let Err(e) = s.send_command(face_cmd).await {
                error!("Failed to send face-monster move: {e}");
                return None;
            }
        }
    }

    // Send attack
    {
        let mut s = state.lock().await;
        let cmd = ClientMessage::PlayerAttack {
            monster_id: monster_id.clone(),
        };
        if let Err(e) = s.send_command(cmd).await {
            error!("Failed to send attack: {e}");
            return None;
        }
    }

    Some(monster_id)
}

pub(super) enum ChaseResult {
    InRange,
    Lost(LostReason),
    Error,
}

/// Why a chase gave up, tagged at the point where the chase loop knew the
/// ground truth — so callers report the real reason instead of guessing.
#[derive(Debug)]
pub(super) enum LostReason {
    /// The target left the world state: died, despawned, or out of sight.
    TargetGone,
    /// We died (or vanished) on the way.
    PlayerDied,
    /// The target sits this far away, beyond the chase's leash.
    TooFar(f32),
    /// The chase clock ran out before arriving.
    Timeout,
    /// No route on this floor — walls or shut doors all the way around.
    NoPath,
}

impl LostReason {
    /// Target-neutral clause completing "You could not reach X — {clause}."
    pub(super) fn clause(&self) -> String {
        match self {
            Self::TargetGone => "your target is no longer there".to_string(),
            Self::PlayerDied => "you died on the way".to_string(),
            Self::TooFar(d) => format!("your target is {d:.0}m away, beyond your reach"),
            Self::Timeout => "you ran out of time before arriving".to_string(),
            Self::NoPath => "no route leads there from here".to_string(),
        }
    }
}

/// What a chase walks toward: a monster (stop at attack range), another
/// character (stop at a polite conversational distance instead of standing
/// on top of them), or a ground item (stop inside pickup range).
pub(super) enum ChaseTarget<'a> {
    Monster(&'a str),
    Player(&'a PlayerId),
    GroundItem(u64),
    /// A fixed world position on a known floor (e.g. the cell beside a chest),
    /// with the distance the caller needs us to end up inside.
    Point {
        pos: onlinerpg_shared::Position,
        floor_level: i8,
        arrive_range: f32,
    },
}

impl ChaseTarget<'_> {
    fn position(&self, s: &SharedState) -> Option<onlinerpg_shared::Position> {
        match self {
            Self::Monster(id) => s.nearby_monsters.get(*id).map(|m| m.position),
            Self::Player(id) => s.nearby_players.get(*id).map(|p| p.position),
            Self::GroundItem(id) => s.ground_item(*id).map(|i| i.position),
            Self::Point { pos, .. } => Some(*pos),
        }
    }

    /// Passability floor index to path toward, converted from the target's
    /// wire `floor_level`.
    fn floor(&self, s: &SharedState) -> u8 {
        let level = match self {
            Self::Monster(id) => s.nearby_monsters.get(*id).map(|m| m.floor_level),
            Self::Player(id) => s.nearby_players.get(*id).map(|p| p.floor_level),
            Self::GroundItem(id) => s.ground_item(*id).map(|i| i.floor_level),
            Self::Point { floor_level, .. } => Some(*floor_level),
        };
        onlinerpg_shared::dungeon::passability_floor_for_level(level.unwrap_or(0))
    }

    /// How the chase paces itself for this kind of target. One row per
    /// variant, so a new target type is a single edit.
    fn tuning(&self) -> ChaseTuning {
        match self {
            // Characters carry a little arrive slack over APPROACH_RANGE so
            // reaching the pulled-back path goal always counts as in range.
            Self::Player(_) => ChaseTuning {
                arrive_range: APPROACH_RANGE + 0.2,
                path_pullback: APPROACH_RANGE,
                step_stop_dist: APPROACH_RANGE,
                max_distance: crate::state::NPC_SIGHT_RADIUS,
                max_secs: MAX_APPROACH_SECS,
                needs_clear_line: false,
            },
            Self::Monster(_) => ChaseTuning {
                arrive_range: ATTACK_RANGE,
                path_pullback: 0.0,
                step_stop_dist: ATTACK_RANGE - 0.5,
                max_distance: MAX_CHASE_DISTANCE,
                max_secs: MAX_CHASE_SECS,
                needs_clear_line: true,
            },
            Self::GroundItem(_) => ChaseTuning {
                arrive_range: PICKUP_ARRIVE_RANGE,
                path_pullback: 0.0,
                step_stop_dist: PICKUP_ARRIVE_RANGE - 0.5,
                max_distance: crate::state::NPC_SIGHT_RADIUS,
                max_secs: MAX_PICKUP_WALK_SECS,
                needs_clear_line: false,
            },
            // A fixed point is only ever offered once we share its room, so
            // the sight radius is slack, not a leash.
            Self::Point { arrive_range, .. } => ChaseTuning {
                arrive_range: *arrive_range,
                path_pullback: 0.0,
                step_stop_dist: (arrive_range - 0.5).max(0.5),
                max_distance: crate::state::NPC_SIGHT_RADIUS,
                max_secs: MAX_POINT_WALK_SECS,
                needs_clear_line: false,
            },
        }
    }
}

/// The distances and deadlines one chase runs by.
struct ChaseTuning {
    /// The chase ends successfully within this distance of the target.
    arrive_range: f32,
    /// How far short of the target the path goal stops, so a step can never
    /// land on top of a character. Zero pathfinds straight at the target —
    /// the arrive check stops us first.
    path_pullback: f32,
    /// How close a direct step (no path) walks before it stops short.
    step_stop_dist: f32,
    /// Give up once the target is further away than this.
    max_distance: f32,
    max_secs: f32,
    /// Arriving also needs a clear attack line — stopping at range through a
    /// shut door is no arrival at all.
    needs_clear_line: bool,
}

/// Log label. `Display` rather than a `-> String` helper so the monster arm
/// keeps borrowing its id instead of allocating a copy for a log line.
impl std::fmt::Display for ChaseTarget<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Monster(id) => f.write_str(id),
            Self::Player(id) => write!(f, "{id}"),
            Self::GroundItem(id) => write!(f, "item {id}"),
            Self::Point { pos, .. } => write!(f, "point ({:.1}, {:.1})", pos.x, pos.z),
        }
    }
}

/// Chase the monster until we're in attack range, using A* pathfinding.
pub(super) async fn chase_monster(
    state: &Arc<Mutex<SharedState>>,
    monster_id: &str,
    sprint: Option<bool>,
) -> ChaseResult {
    chase_target(state, &ChaseTarget::Monster(monster_id), false, sprint).await
}

/// Walk up to another character and stop APPROACH_RANGE short of them,
/// following the target if it moves. Same loop as the combat chase.
pub(super) async fn approach_player(
    state: &Arc<Mutex<SharedState>>,
    player_id: &PlayerId,
    sprint: Option<bool>,
) -> ChaseResult {
    chase_target(state, &ChaseTarget::Player(player_id), false, sprint).await
}

/// The follow task's approach: the same walk, but its steps are background —
/// the task outlives the turn, and steps landing mid-settle must not pass
/// for the running action's result.
pub(super) async fn follow_player(
    state: &Arc<Mutex<SharedState>>,
    player_id: &PlayerId,
    sprint: Option<bool>,
) -> ChaseResult {
    chase_target(state, &ChaseTarget::Player(player_id), true, sprint).await
}

/// Walk to a ground item and stop inside pickup range. Same loop as the
/// combat chase; the target vanishing (picked up or despawned) ends it
/// as `Lost`.
pub(super) async fn walk_to_ground_item(
    state: &Arc<Mutex<SharedState>>,
    instance_id: u64,
    sprint: Option<bool>,
) -> ChaseResult {
    chase_target(state, &ChaseTarget::GroundItem(instance_id), false, sprint).await
}

/// Walk to a fixed position on a floor, stopping within `arrive_range` of it.
pub(super) async fn walk_to_point(
    state: &Arc<Mutex<SharedState>>,
    pos: onlinerpg_shared::Position,
    floor_level: i8,
    arrive_range: f32,
    sprint: Option<bool>,
) -> ChaseResult {
    chase_target(
        state,
        &ChaseTarget::Point {
            pos,
            floor_level,
            arrive_range,
        },
        false,
        sprint,
    )
    .await
}

/// Chase the target until we're within its arrive range, using A*
/// pathfinding. Polls the target position every tick and re-routes when
/// it moves.
async fn chase_target(
    state: &Arc<Mutex<SharedState>>,
    target: &ChaseTarget<'_>,
    background: bool,
    sprint: Option<bool>,
) -> ChaseResult {
    let chase_start = Instant::now();
    let mut path_waypoints: Vec<onlinerpg_shared::pathfinding::PathWaypoint> = Vec::new();
    let mut path_index = 0usize;
    let mut doors_opened = 0usize;
    let mut last_target_x = 0.0f32;
    let mut last_target_z = 0.0f32;
    let tuning = target.tuning();

    loop {
        if chase_start.elapsed().as_secs_f32() > tuning.max_secs {
            warn!("Chase timeout for target {}", target);
            return ChaseResult::Lost(LostReason::Timeout);
        }

        let (in_range, needs_repath, target_pos, target_floor, goal) = {
            let s = state.lock().await;
            let player_alive = s.self_player.as_ref().is_some_and(|p| p.health > 0);
            let Some(target_pos) = target.position(&s) else {
                return ChaseResult::Lost(LostReason::TargetGone);
            };
            if !player_alive {
                return ChaseResult::Lost(LostReason::PlayerDied);
            }

            let player = s.self_player.as_ref().unwrap();
            let to_target = PlanarDelta::between(&player.position, &target_pos);
            let in_range = to_target.dist <= tuning.arrive_range
                && !(tuning.needs_clear_line && s.attack_line_blocked(target_pos.x, target_pos.z));
            if to_target.dist > tuning.max_distance {
                info!(
                    "Giving up chase: target {} is {:.1}m away (>{:.1}m)",
                    target, to_target.dist, tuning.max_distance
                );
                return ChaseResult::Lost(LostReason::TooFar(to_target.dist));
            }

            let target_shift =
                PlanarDelta::xz(last_target_x, last_target_z, target_pos.x, target_pos.z).dist;
            let needs_repath = path_waypoints.is_empty()
                || path_index >= path_waypoints.len()
                || target_shift > REROUTE_THRESHOLD;

            // Path goal, pulled back toward us so the path never ends
            // inside the target character.
            let pullback = tuning.path_pullback;
            let goal = if pullback > 0.0 && to_target.dist > pullback {
                let ratio = (to_target.dist - pullback) / to_target.dist;
                (
                    player.position.x + to_target.dx * ratio,
                    player.position.z + to_target.dz * ratio,
                )
            } else {
                (target_pos.x, target_pos.z)
            };

            (in_range, needs_repath, target_pos, target.floor(&s), goal)
        };

        if in_range {
            return ChaseResult::InRange;
        }

        if needs_repath {
            let (result, underground) = {
                let s = state.lock().await;
                (
                    s.find_path_to(goal.0, goal.1, target_floor),
                    s.self_floor_level < 0,
                )
            };
            // No route underground means a wall or a shut door stands between
            // us and the target — never the open ground the straight-line
            // fallback below assumes. Unlatch what we can, and give up rather
            // than walk a line through the geometry.
            if underground && !result.found {
                if doors_opened < MAX_CHASE_DOORS
                    && open_blocking_door(state, background, sprint).await
                {
                    doors_opened += 1;
                    continue;
                }
                info!("Chase gave up: no route to {target} on this floor");
                return ChaseResult::Lost(LostReason::NoPath);
            }
            if result.waypoints.is_empty() {
                path_waypoints.clear();
            } else {
                path_waypoints = result.waypoints;
            }
            path_index = 0;
            last_target_x = target_pos.x;
            last_target_z = target_pos.z;
        }

        // Step toward next waypoint, subdividing long segments so the chase
        // walks at MOVE_SPEED. Fall back to a direct step toward the target
        // if A* returned no path.
        let (step_dist, sprinting) = if path_index < path_waypoints.len() {
            let wp = path_waypoints[path_index].clone();
            let mut s = state.lock().await;
            let player = match s.self_player.as_ref() {
                Some(p) => p,
                None => return ChaseResult::Lost(LostReason::PlayerDied),
            };
            let to_wp = PlanarDelta::to_xz(&player.position, wp.x, wp.z);

            if to_wp.dist < 0.1 {
                path_index += 1;
                (0.0, false)
            } else {
                let (step_x, step_z, sd) = if to_wp.dist <= MAX_STEP_DIST {
                    path_index += 1;
                    (wp.x, wp.z, to_wp.dist)
                } else {
                    let ratio = MAX_STEP_DIST / to_wp.dist;
                    (
                        player.position.x + to_wp.dx * ratio,
                        player.position.z + to_wp.dz * ratio,
                        MAX_STEP_DIST,
                    )
                };
                match s
                    .send_step(
                        step_x,
                        step_z,
                        wp.floor,
                        to_wp.rotation(),
                        background,
                        sprint,
                    )
                    .await
                {
                    Ok(sprinting) => (sd, sprinting),
                    Err(e) => {
                        error!("Failed to send chase move: {e}");
                        return ChaseResult::Error;
                    }
                }
            }
        } else {
            let mut s = state.lock().await;
            let sprinting = s.sprint_allowed(sprint);
            match compute_step_toward(&s, target, sprinting) {
                Some((cmd, sd)) => {
                    if let Err(e) = s.send_flagged_command(cmd, background).await {
                        error!("Failed to send chase move: {e}");
                        return ChaseResult::Error;
                    }
                    (sd, sprinting)
                }
                None => (0.0, false),
            }
        };

        let step_ms = if step_dist > 0.0 {
            travel_ms(step_dist, sprinting)
        } else {
            CHASE_IDLE_TICK_MS
        };
        tokio::time::sleep(Duration::from_millis(step_ms.max(50))).await;
    }
}

/// Return a single MAX_STEP_DIST-limited move toward the target, plus the
/// step's distance for sleep timing. Used as the fall-through when A* can't
/// return a path (e.g. target on un-pathable terrain) so the chase can still
/// inch the player closer at walk speed. Steps stop short of the target by
/// the tuning's `step_stop_dist`.
fn compute_step_toward(
    state: &SharedState,
    target: &ChaseTarget,
    sprinting: bool,
) -> Option<(ClientMessage, f32)> {
    let target_pos = target.position(state)?;
    let self_player = state.self_player.as_ref()?;

    let to_target = PlanarDelta::between(&self_player.position, &target_pos);
    let stop_dist = target.tuning().step_stop_dist;
    if to_target.dist <= stop_dist {
        return None;
    }

    let target_dist = to_target.dist - stop_dist;
    let step_dist = target_dist.min(MAX_STEP_DIST);
    let ratio = step_dist / to_target.dist;
    let cmd = ClientMessage::PlayerMove {
        position: onlinerpg_shared::Position {
            x: self_player.position.x + to_target.dx * ratio,
            y: target_pos.y,
            z: self_player.position.z + to_target.dz * ratio,
        },
        rotation: to_target.rotation(),
        floor_level: 0,
        append: false,
        sprinting,
    };
    Some((cmd, step_dist))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Wherever we stop, the server has to agree we are in range — it measures
    /// from the chest, we walk to a cell that can be a metre off it.
    #[test]
    fn a_chest_walk_ends_inside_the_server_range() {
        // 0.0: the treasure chest, walked onto directly. 1.0: the cell beside
        // a clutter prop, the only case `beside_prop` can produce.
        for gap in [0.0, 1.0] {
            let stop = gap + chest_arrive_range(gap);
            assert!(
                stop < CHEST_INTERACT_RANGE,
                "stopping {stop}m from a chest {gap}m off the walk target is outside the gate"
            );
        }
    }
}
